from .identifiable import Identifiable
from .terrestrial import Terrestrial
from .aquatic import Aquatic
from .freshwater import Freshwater
from .saltwater import Saltwater
from .flying import Flying
from .walking import Walking
from .swimming import Swimming
from .tree_dwelling import TreeDwelling
from .ground_nester import GroundNester
from .high_elevation import HighElevation